name: ❄ Flake8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install
        run: |
          sudo apt-get install python3-virtualenv virtualenv make

      - name: Init venv
        run: |
          make venv

      - name: Flake8
        run: |
          source venv/bin/activate && flake8 src sammo.py
