name: ❄ Flake8

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  flake8_py3:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2.0.0
        with:
          checkName: 'Python Lint'
          config: .flake8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
