name: "Website"

on: push
  # push:
  #   branches:
  #     - main
  # pull_request:

jobs:
  code:
    name: Website
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install sphinx
        run: sudo apt-get install python3-virtualenv virtualenv
      - name: Build html documentation
        run: virtualenv -p /usr/bin/python3 venv && source venv/bin/activate && pip install sphinx sphinx_rtd_theme && cd doc && make html && cd -
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./doc/build/html/
